### ISSUE TITLE
Landing Page Redesign Not Showing in Production

### ISSUE THREAD

**Issue by lappemic** [protontypes/open-climate-fund#3]
I pushed a redesign of the page to main branch. GitHub Actions ran successfully, but the live site still shows the old version.

Does anyone know why the changes aren't reflected in production? Does it simply still take some time to 'overtake' the changes?

Cc. @Ly0n, @andrew

**Comment by Ly0n** [comment]
![Screenshot from 2024-11-19 16-16-59](https://github.com/user-attachments/assets/7b00b3cb-0892-4160-89e3-c86484c11019)

**Comment by Ly0n** [comment]
I change the **Source** form **GitHub Action** to **Deploy from Branch**. Now it works! Looks great!
